### ISSUE TITLE
@gjanders: Could you give a usage of cmd how to migrate a dashboard from one server to another server. Currently I am testing your script in my local by running two different splunk enterprise version servers on my local with two different ports, one of the server i have the dashboard and i want to migrate that dashboard to other server running in my local with different port. Let me know, if you need any more details

### ISSUE THREAD

**Issue by stelukutla2020** [gjanders/Splunk#15]

**Comment by gjanders** [comment]
`splunk cmd python transfersplunkknowledgeobjects.py -srcURL "https://thesourceserver:8089" -destURL "https://localhost:8089" -srcUsername "admin" -srcPassword "removed" -srcApp sourceAppName -destUsername "admin" -destPassword "changeme" -destApp destAppName -printPasswords -dashboards `

The above would migrate *all* dashboards, you might want just a single one:
`splunk cmd python transfersplunkknowledgeobjects.py -srcURL "https://thesourceserver:8089" -destURL "https://localhost:8089" -srcUsername "admin" -srcPassword "removed" -srcApp sourceAppName -destUsername "admin" -destPassword "changeme" -destApp destAppName -printPasswords -dashboards -includeEntities "just_my_chosen_dashboard"`

**Comment by stelukutla2020** [comment]
> `splunk cmd python transfersplunkknowledgeobjects.py -srcURL "https://thesourceserver:8089" -destURL "https://localhost:8089" -srcUsername "admin" -srcPassword "removed" -srcApp sourceAppName -destUsername "admin" -destPassword "changeme" -destApp destAppName -printPasswords -dashboards `
> 
> The above would migrate _all_ dashboards, you might want just a single one:
> `splunk cmd python transfersplunkknowledgeobjects.py -srcURL "https://thesourceserver:8089" -destURL "https://localhost:8089" -srcUsername "admin" -srcPassword "removed" -srcApp sourceAppName -destUsername "admin" -destPassword "changeme" -destApp destAppName -printPasswords -dashboards -includeEntities "just_my_chosen_dashboard"`

@gjanders It worked , thanks for your help. Its really helpful. But I have to few other tests before adopting this for my use-case
